version: '3'

services:
    postgres:
      container_name: postgres
      image: postgres
      env_file:
        - ./.env
      ports:
        - "5433:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data
    django:
      container_name: django
      build: .
      command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/code
      expose:
        - "8000"
      env_file:
        - ./.env
      depends_on:
        - postgres
    nuxt:
      container_name: nuxt
      build: ./frontend
      ports:
        - "3000:3000"
      expose:
        - "3000"
      command: npm run dev
      volumes:
        - ./frontend:/code
      depends_on:
        - django
    nginx:
      container_name: nginx
      build: ./nginx
      volumes:
        - ./static:/usr/src/app/static
        - ./media:/usr/src/app/media
      ports:
        - "80:80"
      depends_on:
        - nuxt

volumes:
  pg_data:
