# Generated by Django 3.2.15 on 2022-10-01 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('display_order', models.IntegerField(default=0, verbose_name='display_order')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('display_order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('eye_catch', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='eye_catch')),
                ('keywords', models.CharField(max_length=250, verbose_name='keywords')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('body', markdownx.models.MarkdownxField(verbose_name='body')),
                ('page_views', models.PositiveBigIntegerField(default=0, verbose_name='page_views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('is_published', models.BooleanField(default=False, verbose_name='is_published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='category')),
                ('related_posts', models.ManyToManyField(blank=True, related_name='_blog_post_related_posts_+', to='blog.Post', verbose_name='related_posts')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-updated_at',),
            },
        ),
    ]
